### ISSUE TITLE
Atualização do serviço JCenter.

### ISSUE THREAD

**Issue by cesarhilario** [combateafraude/ReactNative#1]
Conforme [nota oficial da Google](https://developer.android.com/studio/build/jcenter-migration), é necessário realizar a migração do serviço JCenter para o MavenCentral. Em [nota oficial](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) a JFrog, empresa que mantém o JCenter, comunicou que o serviço estará disponível por tempo indeterminado.

Eu tentei substituir no build.gradle as chamadas ao jcenter() para mavenCentral(), porém não obtive sucesso no build, este passo foi realizado em outros projetos e funcionou bem, portanto imagino que algum repositório do JCenter não está disponível no Maven Central.

**Comment by dbseitenfus** [comment]
Olá, @cesarhilario 
Obrigado pelo relato, vamos avaliar.

**Comment by murilofank** [comment]
Realizamos a substituição do serviço de repositório do JCenter pelo MavenCentral em nossos projetos, obrigado pelo relato, @cesarhilario.
